### ISSUE TITLE
Feature request: Batch duplicate with Duplication Link

### ISSUE THREAD

**Issue by Kamik** [magicstickuk/multisite-post-duplicator#30]
Is it possible to realize batch duplicate with duplication link?

**Comment by magicstickuk** [comment]
I have considered this but the issue here is there has to be destination site specified, so if you have 5 sites then you would have to have 5 links. That's why I think the drop down action works best. I did also think about the duplicate link opening a modal window where we are asked what site to duplicate to. I think that's a bit overkill from a UI point of view. We're happy with the current batch action checkbox for now.
